### ISSUE TITLE
close issue dont work

### ISSUE THREAD

**Issue by drdelportillo** [jkraemer/redmine_issue_reminder#10]
Hello
First excellent plugin and thanks for sharing
can you tell me how to operate the automatic closure of the incidents
schedule it in the configuration of the plug and never has closed not if I have to do something else
Cheers

**Comment by jkraemer** [comment]
After configuring the plugin you have to execute `rake redmine:close_old_resolved_issues` regularly (i.e. once a week) via cron or similar means. If you do that and it does nothing, a look into the log file should reveal the query that is executed to find issues to be closed, which should help with further diagnosis.

**Comment by drdelportillo** [comment]
thanks for the information help me a lot
