### ISSUE TITLE
Error on v2.6.1

### ISSUE THREAD

**Issue by rohitthakral** [jkraemer/redmine_issue_reminder#6]
I tried running it on Redmine v2.6.1 and it gave me below error:

** Invoke redmine:send_issue_reminders (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Mysql::Error: Access denied for user 'root'@'localhost' (using password: NO)

Redmine is working fine though.

Any clue what is it?

**Comment by jkraemer** [comment]
Most probably its picking up the wrong environment.
