### ISSUE TITLE
Plugin sent all issues to all users

### ISSUE THREAD

**Issue by atopcu** [jkraemer/redmine_issue_reminder#8]
This issue has occurred after upgrade redmine from 2.6 to 3.1. This situation causing the issue security problems.

Thanks for this work. Regards.

Environment:
  Redmine version                3.1.1.stable.14622
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2

**Comment by jkraemer** [comment]
Thanks for the report - which of the rake tasks did that?

**Comment by atopcu** [comment]
Hi jkraemer,
Thanks for reply. Sorry fer delayed response. rake task is send_issue_reminders. other tasks are working correctly.

Regards.

**Comment by jkraemer** [comment]
I cannot reproduce this. Some test cases I just created behave the same in Redmine 2.6, 3.1 and Redmine trunk.
Can you give some more information, i.e. was it really _all_ users being reminded about _all_ inactive issues, or is the problem maybe more subtle?

**Comment by atopcu** [comment]
Hi,
I will re-try when I have a test setup. I can not afford it in the short term.

Thanks for yor help.
